language: ruby
before_install:
  - gem update --system
  - gem install bundler
gemfile:
  - gemfiles/5.0.gemfile
  - gemfiles/5.1.gemfile
  - gemfiles/5.2.gemfile
  - gemfiles/6.0.gemfile
rvm:
  - 2.3.8
  - 2.4.7
  - 2.5.6
  - 2.6.4
script:
  - bundle exec rspec
